version: '3.9'
services:
  db:
    build: ./db
    restart: always
    environment:
      - MONGO_INITDB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
    volumes:
      - rsdo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_EXPRESS_USER}:${MONGO_EXPRESS_PASSWORD}@db:27017/
  dbseed:
    build: ./dbseed
    environment:
      - DBUSER=${DBSEED_USER}
      - DBPASS=${DBSEED_PASS}
      - DBSAFEUSER=${DBSEED_DBSAFEUSER}
      - DBSAFEPASS=${DBSEED_DBSAFEPASS}
    depends_on:
      - db
  sinonimidb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${SINONIMIDB_USER}
      - MARIADB_PASSWORD=${SINONIMIDB_PASS}
      - MARIADB_DATABASE=rsdo
    ports:
      - "3306:3306"
    volumes:
      - "rsdosinonimi:/var/lib/mysql"
      - "./sinonimidb/:/docker-entrypoint-initdb.d/"
  sinonimiapi:
    build: ./sinonimiapi
    depends_on:
      - sinonimidb
    ports:
      - "4000:80"
    environment:
      - DB_HOST=sinonimidb
      - DB_USER=${SINONIMIDB_USER}
      - DB_PASS=${SINONIMIDB_PASS}
      - DB_NAME=rsdo
    volumes:
      - "./sinonimiapi:/var/www/html"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=sinonimidb
  app:
    build: ./app
    restart: always
    ports:
      - ${APP_PORT}:80 # temporaryily changed 3000:80 to 80:80
    volumes:
      - "./app:/usr/src/app"
    depends_on:
      - db
volumes:
  rsdo: null
  rsdosinonimi: null
